Weighted Cross Entropy Implementation
CBICA/GaNDLF pull request #151
Opened 2021-07-24 18:45 UTC by orhunguley

Fixes #141

## Proposed Changes

- Added weighted cross entropy loss to losses.py

## Checklist

- [x] I have read the [`CONTRIBUTING`](https://github.com/CBICA/GaNDLF/blob/master/CONTRIBUTING.md) guide
- [x] My PR is based from the [current GaNDLF master ](https://garygregory.wordpress.com/2016/11/10/how-to-catch-up-my-git-fork-to-master/)
- [x] Non-breaking change (would not break existing functionality): if changes breaks current code, please provide as many details as possible
- [x] Function/class source code documentation added/updated
- [x] Code has been [blacked](https://github.com/psf/black#usage) for style consistency
- [ ] If applicable, version information [has been updated in GANDLF/version.py](https://github.com/CBICA/GaNDLF/blob/master/GANDLF/version.py)
- [ ] If adding a submodule, add to list of expections for black styling in [pyproject.toml](https://github.com/CBICA/GaNDLF/blob/master/pyproject.toml) file 
- [ ] [Usage documentation](https://github.com/CBICA/GaNDLF/blob/master/docs) has been updated, if appropriate
- [ ] [History](https://github.com/CBICA/GaNDLF/blob/master/HISTORY.md) has been updated, if appropriate
- [ ] Tests added or modified to [cover the changes](https://app.codecov.io/gh/CBICA/GaNDLF); if coverage is reduced, please give explanation

2021-07-25 02:57 UTC, sarthakpati requested changes
Hey @orhunguley,

This is a nice PR!

I have 2 suggestions:
1. https://github.com/CBICA/GaNDLF/pull/151#discussion_r676074077
2. The functions `cel` and `weighted_cel` don't need to be separate. Put a single function and pass `params["class_weights"]` (`params["class_weights"]=None` if weights are not calculated [[ref](https://github.com/orhunguley/GaNDLF/blob/master/GANDLF/training_loop.py#L729)], so it should be fine) onward to `torch.nn.CrossEntropyLoss()`. This will reduce the code complexity (and also ensure that the function is tested by the unit tests.

Cheers!

2021-07-25 02:59 UTC, sarthakpati commented on GANDLF/utils.py
> +    weights_dict = {key: val / normalizer for key, val in abs_dict.items()}
```suggestion
    weights_dict = {key: val / total_counter for key, val in abs_dict.items()}
```

2021-07-28 23:58 UTC, sarthakpati commented on GANDLF/losses.py
> +            class_weights = class_weights.cpu()
```suggestion
        class_weights .float().to(params["device"])
```

2021-07-29 02:57 UTC, sarthakpati approved these changes
Needed a few more fixes, which I have pushed.

2021-07-29 03:15 UTC, merged

2021-07-29 13:38 UTC, orhunguley commented
Hi @sarthakpati  
I am not sure if removing cuda() check for "out" in weighted cel calculation would work. Because even though we have the device as "cuda", the validation is all cpu based and would cause errors. I will check it and let you know.

2021-07-29 13:40 UTC, sarthakpati commented
Sure thing. I checked on my location machine for both CPU and GPU and it did seem to work as expected.

2021-07-29 14:19 UTC, orhunguley commented
> Sure thing. I checked on my local machine for both CPU and GPU and it did seem to work as expected.

I got an error. Can you also try it on your GPU machine? Maybe you did not wait until validation, that is why you did not encounter any errors?

2021-07-29 14:30 UTC, sarthakpati commented
Understood. Put in a simple fix: #153

Thanks!