Adding more details to the average_probabilities.csv file for classification tasks
CBICA/GaNDLF pull request #326
Opened 2022-03-05 00:25 UTC by orhunguley

This PR will add more details to "average_probabilities.csv" file, which should be created after running inference for classification models. An example file is attached.[averaged_probabilities.csv](https://github.com/CBICA/GaNDLF/files/8189415/averaged_probabilities.csv)

## Proposed Changes

- Added headers to the file, "SubjectID", "PredictedClass", "ClassName"

## Checklist

- [ x] I have read the [`CONTRIBUTING`](https://github.com/CBICA/GaNDLF/blob/master/CONTRIBUTING.md) guide
- [x ] My PR is based from the [current GaNDLF master ](https://garygregory.wordpress.com/2016/11/10/how-to-catch-up-my-git-fork-to-master/)
- [ x] Non-breaking change (would not break existing functionality): please provide as many details as possible for any breaking change 
- [x ] Function/class source code documentation added/updated
- [x ] Code has been [blacked](https://github.com/psf/black#usage) for style consistency
- [ x] If applicable, version information [has been updated in GANDLF/version.py]
- [x ] If adding a git submodule, add to list of exceptions for black styling in [pyproject.toml](https://github.com/CBICA/GaNDLF/blob/master/pyproject.toml) file 
- [x ] [Usage documentation](https://github.com/CBICA/GaNDLF/blob/master/docs) has been updated, if appropriate
- [ x] [History](https://github.com/CBICA/GaNDLF/blob/master/HISTORY.md) has been updated, if appropriate
- [x ] Tests added or modified to [cover the changes](https://app.codecov.io/gh/CBICA/GaNDLF); if coverage is reduced, please give explanation

2022-03-05 02:52 UTC, sarthakpati requested changes
Looks good, just need to remove the commented out lines since they appear to be redundant.

2022-03-05 02:52 UTC, sarthakpati commented on GANDLF/compute/forward_pass.py
> +            # )
```suggestion
```

2022-03-05 02:52 UTC, sarthakpati commented on GANDLF/inference_manager.py
> +        # columns = ["SubjectID",] + parameters["model"]["class_list"]
```suggestion
```

2022-03-05 02:52 UTC, sarthakpati commented on GANDLF/inference_manager.py
> +        # )
```suggestion
```

2022-03-06 14:10 UTC, orhunguley reviewed
removed the commented out lines.

2022-03-06 23:28 UTC, sarthakpati commented on GANDLF/inference_manager.py
> +            os.path.join(outputDir, "averaged_probabilities.csv"), index=False, sep=","
```suggestion
            os.path.join(outputDir, "final_predictions_with_averaged_probabilities.csv"), index=False, sep=","
```

2022-03-06 23:28 UTC, sarthakpati approved these changes
LGTM!

2022-03-07 11:51 UTC, sarthakpati commented
This is merged.

2022-03-07 11:51 UTC, closed without merging